# PROPIEDADES DE DESARROLLO
app.version=${project.version}

app.products.id-payment-product=1
app.products.top-up-comission=491
app.products.top-up-product=542
app.products.proteced=1,494,545

app.categories.protected=1

app.paymnts.comission-rate=1.05

db.url=jdbc:mysql://127.0.0.1:3306/blo-sales-v2
db.username=root
db.password=root
db.driver=com.mysql.cj.jdbc.Driver